### ISSUE TITLE
Sequenced assembly for all incriber presses make calculation press only.

### ISSUE THREAD

**Issue by akanealw** [dryas-octopetala/ae2_create_evecompat_data#1]
I'm on 1.20.1 Fabric with Create ver. 0.5.1-f. When I run the sequenced assemblies for the presses, all of the four different recipes make a calculation press at the end after the spout lava.

I was also wondering if it would be possible to make the presses similar to sand paper where you can put it in a deployer and reuse it multiple times. For the printed silicon and circuits, the press would be in the deployer instead of the raw material. Given that you only start with one of each it would be nice to be able to reuse them. If you put durability on them, there would still be a need to create new presses.

Thanks!

**Comment by dryas-octopetala** [comment]
Hi! Thanks for telling me! I'll reply again when it's fixed. I thought I had tested it so I wonder if I accidentally reverted those recipes to the template I had...

In regards to the resource usage for the presses, my vision for the recipe is needless automation. It's relatively simple to create a ton of the presses which is why they get consumed instead of reused. Because it circumvents the AE2 world gen and inscriber mechanics I decided on an "either or" theme with this datapack so I probably won't include a sandpaper type functionality.

**Comment by akanealw** [comment]
ah, that's a fair point.

**Comment by dryas-octopetala** [comment]
So it looks like internally the create recipe sequence ignores NBT tags. I thought it would be fine if the transitional item was clay for everything because it gives a recipe id after the first deploying sequence. It looks like I'm going to have to use clay, gravel, sus sand, concrete, and sus gravel instead :) (Trying to keep the real world process of clay-sand casting visually intact).

Given more time I can add real transitional items instead... I hate to do a botched fix like above..

**Comment by dryas-octopetala** [comment]
> I'm on 1.20.1 Fabric with Create ver. 0.5.1-f. When I run the sequenced assemblies for the presses, all of the four different recipes make a calculation press at the end after the spout lava.
> 
> I was also wondering if it would be possible to make the presses similar to sand paper where you can put it in a deployer and reuse it multiple times. For the printed silicon and circuits, the press would be in the deployer instead of the raw material. Given that you only start with one of each it would be nice to be able to reuse them. If you put durability on them, there would still be a need to create new presses.
> 
> Thanks!

Fixed! Wanted to make sure everything was up to par. New version below! I changed the recipe entirely and added transitional items for every sequenced assembly recipe :)

https://modrinth.com/mod/ae2_create_evecompat/version/1.0.0+mc1.20.1-fabric
